# Base URL for Zenodo files
ZENODO_URL: "https://zenodo.org/records/17582711/files/"

# List of Singularity image files (on Zenodo)
SIF_LIST: [
    "downloading_fastq.sif",
    "featurecounts.sif",
    "mapping.sif",
    "trimming.sif"
]

# Number of threads to use
THREADS: 4

# List of SRR identifiers
SRR_LIST: ["SRR10379721", "SRR10379722", "SRR10379723", "SRR10379724", "SRR10379725", "SRR10379726"]

# Trimming parameters
QUALITY: 20
PHRED: 33
MINLEN: 25